services:
  postgres:
    image: postgres:16-alpine
    container_name: abp_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-secretaria_db}
      POSTGRES_USER: ${POSTGRES_USER:-secretaria_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretaria_pass}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-secretaria_user} -d ${POSTGRES_DB:-secretaria_db}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - internal_net

  backend:
    build:
      context: ./backend
      target: dev
    container_name: abp_backend
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://secretaria_user:secretaria_pass@postgres:5432/secretaria_db
      CORS_ORIGIN: http://localhost:5173
      JWT_SECRET: fatec_jacarei_super_secreta_2026_abp_oficial
      JWT_EXPIRES_IN: 8h
      SMTP_HOST: sandbox.smtp.mailtrap.io
      SMTP_PORT: 2525
      SMTP_USER: 4b59c36739dc4d
      SMTP_PASS: c10f624c56492b
      # SMTP_HOST: smtp.gmail.com
      # SMTP_PORT: 587
      # SMTP_USER: o_email_do_projeto@gmail.com
      # SMTP_PASS: aquela_senha_de_16_letras_gerada_pelo_google
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - internal_net

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: abp_frontend
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
    networks:
      - internal_net

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: abp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - internal_net

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
  pgadmin_data:

networks:
  internal_net:
    driver: bridge

